version: "3.9"

services:
  imagepixelator:
    build: .
    container_name: imagePixelator
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.imagepixelator.rule=Host(`imagepixelator.localhost`)"
      - "traefik.http.services.imagepixelator.loadbalancer.server.port=80"
    networks:
      - localweb

networks:
  localweb:
    external: true